#road
NUM_NODES = 30
MAX_LANES=5
MAX_DEGREE = 4
EDGE_PROB = 0.1
FORCE_SINGLE_ROAD = [15]
CONNECTION_LIMIT = 5
RING = True

#cars
NUM_CARS_INITIALLY = 30
NEW_CAR_PROB = 0.05

#video
FPS = 30
SPEED = 1
FRAMES = 6000
SHOW_MID_PROCESS = False
FRAMES_PER_OUTPUT=20
GENERATE_GIF = False